### ISSUE TITLE
corona help 수정을 통한 접근성 향상

### ISSUE THREAD

**Issue by Wonchul-Shin** [20-2-SKKU-OSS/2020-2-OSS-2#10]
corona-cli에는 많은 기능들이 있고 해당 기능들을 검색하는 기능인 corona help를 지원한다.
하지만 corona help 기능에서 작성된 글을 보고 기능을 완전히 파악하는 것이 힘들다고 느꼈고 
cli.js 파일을 편집하여 이용자들이 더 편하게 corona 프로그램을 이용할 수 있도록 한다.

**Comment by Yanghyeondong** [comment]
현재까지 신원철님이 `help` 에 많은 기여를 하신것으로 알고있습니다.
혹시 가능하시면, 간단하게라도 개선하신 부분을 기록해 놓으면 좋을것 같습니다!
기능 개선에 참여해주셔서 감사합니다!
