### ISSUE TITLE
포괄적인 국가 이름 전체 적용(ex. corona ROK --chart)-기능 개선

### ISSUE THREAD

**Issue by Yanghyeondong** [20-2-SKKU-OSS/2020-2-OSS-2#16]
지난 이슈였던

> 포괄적인 국가 검색(ex. S. korea -> korea)-기능 개선

에서 사용한 기능을 corona-cli 의 타 기능 (ex. --chart) 등에 적용할 예정입니다. (이현재님 조언 감사드립니다.)
현재 제가 생각하는 적용 범위는 다음과 같습니다.

--chart
~~--bar~~
~~--sort~~

혹시나 제가 빠트린 부분이 있으면 코멘트 남겨주세요.

## (수정!) 
--bar 기능과 --sort 기능의 경우 특정 국가의 이름을 인자로 넣지 않는것 같습니다. 아래가 원본 프로젝트의 사용법 입니다.

> Bar Charts
> Print bar charts for max 10 countries.
> corona --bar
> corona -b
> Print bar charts for top 5 countries w.r.t deaths.
> corona --bar --sort deaths --limit 5
> corona -b -s deaths -l 5
> Print bar charts countries w.r.t recovered cases.
> corona --bar --sort recovered
> corona -b -s recovered

> Sort Data
> Sort data by type
> corona --sort country              참고: countryName 과 country 는 별개
> corona --s cases
> All sorting parameters.
> corona -s country
> corona -s cases
> corona -s cases-today
> corona -s deaths
> corona -s deaths-today
> corona -s recovered
> corona -s active
> corona -s critical
> corona -s per-million
> Reverse sort data
> corona --sort active --reverse
> corona -s active -r

**혹시나 제가 잘못알고 있는 것이라면 코멘트 남겨주세요!**

**Comment by dlguswo333** [comment]
아 맞네요 그러면 차트만 넣어주시면 되겠어요
