### ISSUE TITLE
대륙별 COVID-19 정보 

### ISSUE THREAD

**Issue by JEONYUNTAE** [20-2-SKKU-OSS/2020-2-OSS-2#2]
대륙별로 감염자에 관한 정보를 제공해주는 기능

from: [issue#99](https://github.com/ahmadawais/corona-cli/issues/99)

**Comment by dlguswo333** [comment]
https://corona.lmao.ninja/v2/countries/kr
corona-cli가 정보를 받아오는 주소로 들어가 보시면 continent에 대한 정보가 나와 있습니다.
해당 정보를 이용하면 유용하겠네요

**Comment by dlguswo333** [comment]
6일 전에 열렸는데 아직 아무도 안 하셔서 제가 한 번 해보겠습니당.

**Comment by JEONYUNTAE** [comment]
넵 부탁드려요!
