### ISSUE TITLE
sort data 추출 기능 입력의 간편화

### ISSUE THREAD

**Issue by jung-jae-yoon** [20-2-SKKU-OSS/2020-2-OSS-2#21]
cases ->c
cases-today -> c-t
deaths -> d
deaths-today -> d-t
recovered -> r
active -> a
critical -> c
per-million -> p-m
위와 같은 방식으로 입력시에도 데이터들을 가져올수 있게 하여 사용시 편리함을 높인다

**Comment by Yanghyeondong** [comment]
좋은 기능인것 같습니다!
가능하다면 `--help` 명령어에 해당 간편화의 대응을 `(ex. cases ->c)`  추가해 주면 사용자 입장에서 더욱 편리할것 같습니다.

**Comment by Wonchul-Shin** [comment]
저도 death-today를 모두 치는 것이 번거로울 수 있다고 생각했는데 
좋은 아이디어인것같습니다!!

**Comment by JEONYUNTAE** [comment]
[pull-request#25](https://github.com/20-2-SKKU-OSS/2020-2-OSS-2/pull/25#issuecomment-735342987)

풀리퀘스트 까지 마치셔서 이슈 닫겠습니다.
