### ISSUE TITLE
위험 국가 리스트 출력 옵션 - 기능 추가

### ISSUE THREAD

**Issue by Yanghyeondong** [20-2-SKKU-OSS/2020-2-OSS-2#22]
`--danger` 옵션을 통해 전세계 나라 중 위험국가 리스트를 출력해주는 기능을 만들려고 합니다.
여기서 말하는 **위험국가** 의 기준은 다음과 같이 생각하고 있습니다. (기준의 중복은 or로 판단됩니다.)

- 현재 해당 국가의 확진자 수 Per Million이 전 세계 Per Million 의 3배 이상인 경우
- 현재 해당 국가의 확진자 수 Per Million이 전 세계 상위 10%인 경우

**추가**

- 최근(대락 1달) 100,000명당 누적 신규 사례수가 100 명 이상인 경우 (혹은1,000,000명 당 1000명 이상)

> Centers for Disease Control and Prevention 의 여행 보건고지 레벨 4 매우 높음 인용

해당 기능은 추가적인 js 파일을 만들어서 구현할 예정입니다.
또한, `--help` 에도 설명을 추가할 예정입니다.
혹시나 추가적인 의견있으면 말씀해 주세요.

## 수정!!
앞서 위험국가의 기준으로 정했던 
- 최근(대락 1달) 100,000명당 누적 신규 사례수가 100 명 이상인 경우 (혹은1,000,000명 당 1000명 이상)

을 위해서 다음과 같이 axios 모듈로 개별 국가의 최근 히스토리를 전부 불러오니 시간이 너무 오래걸렸습니다.

> axios.get(`https://corona.lmao.ninja/v2/historical/${oneCountry.country}`)

![image](https://user-images.githubusercontent.com/37038105/100535282-d9f3a180-325a-11eb-96e6-52f91911eda2.png)

빠른 응답속도를 지향하는 corona-cli 의 특성상 시간지연은 큰 단점이 될수 있으므로, 해당 기능의 속도 개선 방법을 찾을때 까지는
확진자 수 Per Million 을 기준으로 위험국가를 분류하겠습니다.
추가적으로, corona-cli 에서 제공하는 확진자 수 Per Million 은 모두 현재 확진자 수를 기반으로 하고있으므로 "최근 28일 데이터" 보다는 최신성이 좀 떨어지지만 코로나의 잠복기와 치료기간을 생각했을때 위험국가의 지표로 어느정도는 적합한 것 같습니다.

**Comment by Wonchul-Shin** [comment]
위험국가를 명시해주는 것은 정말 좋은 아이디어인것 같습니다. 다만 "확진자 수 Per Million이 전 세계 Per Million 의 3배 이상인 국가"가 국가의 현재 위험도를 표현하는 수치로는 조금 부족할 수도 있다는 걱정이 듭니다. 인구 백만명당 최근 사망자 또는 확진자 같은 지표로 평가하는 것은 어떨까요?  
찾아보니 CDC에서는 국가의 위험도를 최근 28일 동안 100,000명당 누적 신규 사례수로 평가하는 것 같습니다. 
https://korean.cdc.gov/coronavirus/2019-ncov/travelers/how-level-is-determined.html

**Comment by Yanghyeondong** [comment]
의견 감사드립니다!
알려주신 [https://korean.cdc.gov/coronavirus/2019-ncov/travelers/how-level-is-determined.html](url) 사이트를 기반으로
새로운 기준을 추가하겠습니다.
