### ISSUE TITLE
Bar chart 기능 입력의 간편화

### ISSUE THREAD

**Issue by jung-jae-yoon** [20-2-SKKU-OSS/2020-2-OSS-2#26]
sort data 추출 기능 입력의 간편화를 bar chart 기능에도 확대 적용 하고자 합니다.

**Comment by Yanghyeondong** [comment]
사용자의 편의성을 개선하는 매우 좋은 이슈라고 생각합니다.
혹시 가능하시면, 몇몇 예시를 적어주면 더욱 직관적으로 와닿을것 같습니다.
어사인에 정재윤님을 등록해놓겠습니다. 만약에 추가적인 내용이 있으면 바로 올려주세요!

**Comment by jung-jae-yoon** [comment]
cases ->c
cases-today -> c-t
deaths -> d
deaths-today -> d-t
recovered -> r
active -> a
critical -> c
per-million -> p-m
예시는 위와 같습니다
bar chart 기능은 sort data를 입력 받아 값이 높은 나라 순서로 그래프를 제공하는데, sort data를 입력할때 번거로움을 줄이고자 위와같은 간편화 기능을 추가시켜 보려고 합니다

**Comment by JEONYUNTAE** [comment]
### [Pull-request#37](https://github.com/20-2-SKKU-OSS/2020-2-OSS-2/pull/37)

코드 리뷰 후 머지해드려서 해당 이슈 닫도록 하겠습니다.
