### ISSUE TITLE
[ASK] 위험 국가 지표에 대한 의견 요청

### ISSUE THREAD

**Issue by Yanghyeondong** [20-2-SKKU-OSS/2020-2-OSS-2#32]
우선 해당 이슈를 연 이유는 위험 국가에 지표에 대한 여러분의 의견을 수렴하기 위해서입니다.
저번 이슈에서는 시간지연 문제로 각 국가별 최신데이터 수집에 어려움이 있었으나, 지금은 해결되었습니다.

[위험 국가 리스트 출력 옵션 - 기능 추가 #22](https://github.com/20-2-SKKU-OSS/2020-2-OSS-2/issues/22)

다만, 기능을 구현하고나니 다음과 같은 문제가 발생했습니다.
저번 이슈에서 저는  신원철님의 의견과 함께 위험국가의 지표로 다음 조건이 적절하다고 생각했습니다.
- 최근(대락 1달) 100,000명당 누적 신규 사례수가 100 명 이상인 경우

> Centers for Disease Control and Prevention 의 여행 보건고지 레벨 4 매우 높음 인용

그러나 위의 조건을 현재 corona-cli에 적용할 경우, 대략 220 개국 정도 중에서 대략 120개국이 위험국가로 분류가 됩니다.
(다행히 한국은 포함되지 않는군요). 절반이 넘는 국가가 위험 국가로 선정되는 것은 위험 국가 알림이라는 기능의 의미를 
퇴색시킨다고 생각하는데, 여러분의 의견은 어떤지 궁금합니다. 자유롭게 코멘트 남겨주세요!

**Comment by dlguswo333** [comment]
아무래도 CDC가 전문기관이니까 CDC의 기준을 따르는게 맞다고 생각합니다.
절반이 넘는 국가가 위험국가로 분류되는 것도 다르게 생각하면 그만큼 전세계적으로 코로나가 심각하다는 의미를 보여주기도 하구요.
대신 원래 있는 limit 기능은 살리는 방식으로 사용자가 원하는 만큼만 볼 수 있게 하는 방향으로 나아가는게 좋다고 생각합니다.

**Comment by Yanghyeondong** [comment]
의견 감사합니다! 
현재님의 말씀처럼 위험국가가 좀 많더라도 CDC의 기준을 따르는 것이 맞는것 같습니다.
그리고 코드를 다시 검증해본 결과,  `https://corona.lmao.ninja/v2/historical` 사이트에 동일한 국가명이 여러개 반복됨을 확인했습니다.
해당 중복 버그를 해결하니 (사이트 수정이 아닌 코드내 받아오는 정보수정) 대략 80개국으로 좁혀졌습니다.
limit 기능의 경우, sorting 기능과 맞물리는 지라 수정에 조금 시간이 걸릴 듯 합니다. 
해당 수정은 오늘내로 풀리퀘스트 하도록 하겠습니다. 감사합니다.
