### ISSUE TITLE
포괄적인 국가 검색(ex. S. korea -> korea)-기능 개선

### ISSUE THREAD

**Issue by Yanghyeondong** [20-2-SKKU-OSS/2020-2-OSS-2#9]
현재 `corona S. korea` 가 아닌 `corona korea` 명령어를 사용하면 
`Oops. A country named "korea" doesn't exist…`
위 같은 오류가 발생한다. 
따라서 좀 더 포괄적인 국가 검색을 위해  기능을 개선하려고 한다.

해당 개선의 구체적인 방법은 다음과 같다.

getCountry.js 파일의 `axios.get(https://corona.lmao.ninja/v2/countries/${countryList[i]})`
함수를 호출하기 전, countryList[i] 를 전처리하는 함수를 따로 만든다.
전처리 함수에서는 korea 와 같이 corona.lmao.ninja 에 존재하지 않는 국가를
S. korea 같이 존재하는 국가의 형태로 바꾸어 준다.

만약 S. korea -> korea 와 같이 포괄적인 검색 케이스가 생각나는 것이 있다면,
코멘트로 남겨주길 바란다.

**Comment by Wonchul-Shin** [comment]
일단 ROK (Repulic of korea)는  없네요.. 
한국어로도 나라 검색 지원되게 하는건 너무 번잡할까요??

**Comment by dlguswo333** [comment]
https://corona.lmao.ninja/v2/countries/${countyName}
해당 사이트에서 A country name, iso2, iso3, or country ID code는 알아서 해석해 주는데
korea는 아닌가 봅니다.
모든 나라의 모든 이름에 대해 다 하는 건 번잡하기도 하니까 한국에 대해서만 하는 건  괜찮지 않을까요?

**Comment by Yanghyeondong** [comment]
> 일단 ROK (Repulic of korea)는 없네요..
현재 "ROK" 를 포함해서 "korea", "Korea", "S.Korea", "southkorea", "SouthKorea",
"Hanguk", "hanguk" 를 추가한 상태입니다. 의견 감사합니다!

> 한국어로도 나라 검색 지원되게 하는건 너무 번잡할까요??
제가 한국어를 시도해본 결과, 이전과는 다른 오류가 발견되었습니다.
아마 한글문자를 사용하는 것 자체에서 근본적으로 문제가 발생하는 것 같습니다. 
따라서 한국어로도 검색 지원되게 하는것은 보류하거나, 혹은 또다른 이슈로 만들어서 진행하는것이 좋을듯 합니다.

>해당 사이트에서 A country name, iso2, iso3, or country ID code는 알아서 해석해 주는데 korea는 아닌가 봅니다.
맞습니다. 국가코드 등은 지원이 되지만 "korea" 는 지원이 되지 않았습니다.

>모든 나라의 모든 이름에 대해 다 하는 건 번잡하기도 하니까 한국에 대해서만 하는 건 괜찮지 않을까요?
우선 모든 나라에 대해서 하는 것은 확실히 무리인것 같습니다. 다만, 현재 한국을 해본 결과 몇개의 국가만 더 추가하는것 정도는 
어렵지 않은것 같습니다. 따라서 주요 국가 3~4 개 정도만 더 할까 생각 중입니다. 좋은의견 감사드립니다!

**Comment by dlguswo333** [comment]
지금 getCountry.js에서만 해당 모듈을 사용하고 있는데, 나중에 다른 모듈에서도 사용가능하게 수정부탁드립니다.
다시 마음이 내키시면 이슈 reopen 해주시고 작업해주세요.
